window.TOOLS = [
  { slug: "image-to-png", name: "Image to PNG Converter", cat: "image", desc: "Convert any image to PNG in your browser.", icon: "🖼️" },
  { slug: "image-to-jpg", name: "Image to JPG Converter", cat: "image", desc: "Export photos as JPG with quality control.", icon: "🌄" },
  { slug: "image-resizer", name: "Image Resizer", cat: "image", desc: "Resize images to exact pixel dimensions.", icon: "↔️" },
  { slug: "image-compressor", name: "Image Compressor", cat: "image", desc: "Shrink file size while keeping visuals sharp.", icon: "🗜️" },
  { slug: "image-cropper", name: "Image Cropper", cat: "image", desc: "Crop a region from an image and download it.", icon: "✂️" },
  { slug: "image-to-base64", name: "Convert Image to Base64", cat: "image", desc: "Turn an image into a Base64 data URI.", icon: "🔤" },
  { slug: "webp-to-png", name: "Convert WebP to PNG", cat: "image", desc: "Decode WebP and save as PNG.", icon: "🔄" },
  { slug: "gif-maker", name: "GIF Maker", cat: "image", desc: "Stitch frames into an animated GIF.", icon: "🎞️" },
  { slug: "qr-code-generator", name: "QR Code Generator", cat: "image", desc: "Create a QR code from any text or URL.", icon: "▦" },
  { slug: "screenshot-to-pdf", name: "Screenshot to PDF Converter", cat: "image", desc: "Pack screenshots into a printable PDF.", icon: "📄" },
  { slug: "meta-tag-generator", name: "Meta Tag Generator", cat: "seo", desc: "Build title, description, and social meta tags.", icon: "🏷️" },
  { slug: "keyword-density-checker", name: "Keyword Density Checker", cat: "seo", desc: "Measure how often terms appear in copy.", icon: "📊" },
  { slug: "sitemap-generator", name: "Sitemap Generator", cat: "seo", desc: "Create an XML sitemap from a URL list.", icon: "🗺️" },
  { slug: "robots-txt-generator", name: "Robots.txt Generator", cat: "seo", desc: "Produce a robots.txt file with rules.", icon: "🤖" },
  { slug: "google-index-checker", name: "Google Index Checker", cat: "seo", desc: "Build a site: search to inspect index coverage.", icon: "🔍" },
  { slug: "domain-authority-checker", name: "Domain Authority Checker", cat: "seo", desc: "Heuristic URL strength checklist (not Moz DA).", icon: "📈" },
  { slug: "backlink-checker", name: "Backlink Checker", cat: "seo", desc: "Extract links from pasted HTML or a page list.", icon: "🔗" },
  { slug: "page-speed-checker", name: "Page Speed Checker", cat: "seo", desc: "Audit pasted HTML for common speed issues.", icon: "⚡" },
  { slug: "xml-sitemap-validator", name: "XML Sitemap Validator", cat: "seo", desc: "Validate sitemap XML structure in-browser.", icon: "✅" },
  { slug: "mobile-friendly-test", name: "Mobile-Friendly Test", cat: "seo", desc: "Check viewport and tap-target hints in HTML.", icon: "📱" },
  { slug: "word-counter", name: "Word Counter", cat: "text", desc: "Count words, sentences, and reading time.", icon: "📝" },
  { slug: "character-counter", name: "Character Counter", cat: "text", desc: "Track characters with and without spaces.", icon: "🔢" },
  { slug: "case-converter", name: "Case Converter", cat: "text", desc: "Switch text between common letter cases.", icon: "Aa" },
  { slug: "plagiarism-checker", name: "Plagiarism Checker", cat: "text", desc: "Compare two texts for overlap (local similarity).", icon: "📚" },
  { slug: "grammar-checker", name: "Grammar Checker", cat: "text", desc: "Catch basic grammar and punctuation issues.", icon: "✏️" },
  { slug: "text-to-speech", name: "Text-to-Speech", cat: "text", desc: "Speak text aloud with the Web Speech API.", icon: "🔊" },
  { slug: "speech-to-text", name: "Speech-to-Text", cat: "text", desc: "Dictate notes using your microphone.", icon: "🎤" },
  { slug: "url-encoder-decoder", name: "URL Encoder & Decoder", cat: "text", desc: "Encode or decode URL components.", icon: "🌐" },
  { slug: "fancy-text-generator", name: "Fancy Text Generator", cat: "text", desc: "Stylize text with Unicode letter forms.", icon: "✨" },
  { slug: "random-text-generator", name: "Random Text Generator", cat: "text", desc: "Generate lorem-style placeholder copy.", icon: "🎲" },
  { slug: "json-formatter", name: "JSON Formatter", cat: "developer", desc: "Pretty-print or minify JSON safely.", icon: "{}" },
  { slug: "html-to-markdown", name: "HTML to Markdown Converter", cat: "developer", desc: "Turn HTML markup into Markdown.", icon: "⬇️" },
  { slug: "css-minifier", name: "CSS Minifier", cat: "developer", desc: "Minify CSS by stripping comments and space.", icon: "#" },
  { slug: "javascript-minifier", name: "JavaScript Minifier", cat: "developer", desc: "Light minify for JS (no bundler needed).", icon: "JS" },
  { slug: "sql-formatter", name: "SQL Formatter", cat: "developer", desc: "Add readable whitespace to SQL statements.", icon: "🗃️" },
  { slug: "htaccess-redirect-generator", name: "HTACCESS Redirect Generator", cat: "developer", desc: "Create Apache redirect rules.", icon: "↪️" },
  { slug: "markdown-to-html", name: "Markdown to HTML Converter", cat: "developer", desc: "Convert Markdown to HTML fragments.", icon: "⬆️" },
  { slug: "color-code-picker", name: "Color Code Picker", cat: "developer", desc: "Pick a color and copy HEX, RGB, and HSL.", icon: "🎨" },
  { slug: "base64-encoder-decoder", name: "Base64 Encoder & Decoder", cat: "developer", desc: "Encode or decode Base64 strings.", icon: "🔐" },
  { slug: "ip-address-lookup", name: "IP Address Lookup", cat: "developer", desc: "Look up your public IP and basic geo data.", icon: "🖥️" },
  { slug: "percentage-calculator", name: "Percentage Calculator", cat: "calculators", desc: "Solve percent-of, increase, and difference.", icon: "%" },
  { slug: "age-calculator", name: "Age Calculator", cat: "calculators", desc: "Exact age from a date of birth.", icon: "🎂" },
  { slug: "bmi-calculator", name: "BMI Calculator", cat: "calculators", desc: "Body mass index with category labels.", icon: "⚖️" },
  { slug: "loan-emi-calculator", name: "Loan EMI Calculator", cat: "calculators", desc: "Monthly EMI, interest, and total payable.", icon: "🏦" },
  { slug: "scientific-calculator", name: "Scientific Calculator", cat: "calculators", desc: "Trig, logs, powers, and constants.", icon: "🧮" },
  { slug: "discount-calculator", name: "Discount Calculator", cat: "calculators", desc: "Sale price after percent off.", icon: "🏷️" },
  { slug: "currency-converter", name: "Currency Converter", cat: "calculators", desc: "Live rates via the Frankfurter API.", icon: "💱" },
  { slug: "time-zone-converter", name: "Time Zone Converter", cat: "calculators", desc: "Convert a time between time zones.", icon: "🕒" },
  { slug: "binary-to-decimal", name: "Binary to Decimal Converter", cat: "calculators", desc: "Convert binary, decimal, hex, and octal.", icon: "01" },
  { slug: "tip-calculator", name: "Tip Calculator", cat: "calculators", desc: "Split a bill with tip percentage.", icon: "💸" },
  { slug: "length-converter", name: "Length Converter", cat: "converters", desc: "Metric and imperial lengths.", icon: "📏" },
  { slug: "weight-converter", name: "Weight Converter", cat: "converters", desc: "Mass units from milligrams to tons.", icon: "⚖️" },
  { slug: "speed-converter", name: "Speed Converter", cat: "converters", desc: "km/h, mph, knots, and more.", icon: "🚗" },
  { slug: "temperature-converter", name: "Temperature Converter", cat: "converters", desc: "Celsius, Fahrenheit, and Kelvin.", icon: "🌡️" },
  { slug: "volume-converter", name: "Volume Converter", cat: "converters", desc: "Liters, gallons, cups, and cubic units.", icon: "🧪" },
  { slug: "data-storage-converter", name: "Data Storage Converter", cat: "converters", desc: "Bits, bytes, and binary prefixes.", icon: "💾" },
  { slug: "energy-converter", name: "Energy Converter", cat: "converters", desc: "Joules, calories, kWh, and BTU.", icon: "⚡" },
  { slug: "pressure-converter", name: "Pressure Converter", cat: "converters", desc: "Pa, bar, PSI, and atmospheres.", icon: "⏲️" },
  { slug: "fuel-efficiency-converter", name: "Fuel Efficiency Converter", cat: "converters", desc: "mpg, km/L, and L/100km.", icon: "⛽" },
  { slug: "angle-converter", name: "Angle Converter", cat: "converters", desc: "Degrees, radians, and gradians.", icon: "📐" },
  { slug: "md5-hash-generator", name: "MD5 Hash Generator", cat: "security", desc: "MD5 digest for text (checksums, not passwords).", icon: "#️⃣" },
  { slug: "sha256-hash-generator", name: "SHA256 Hash Generator", cat: "security", desc: "SHA-256 hash with Web Crypto.", icon: "🔒" },
  { slug: "password-generator", name: "Password Generator", cat: "security", desc: "Create strong random passwords.", icon: "🔑" },
  { slug: "random-string-generator", name: "Random String Generator", cat: "security", desc: "Random strings with charset options.", icon: "🧬" },
  { slug: "url-shortener", name: "URL Shortener", cat: "security", desc: "Create a local short link stored in this browser.", icon: "📎" },
  { slug: "ip-geolocation-finder", name: "IP Geolocation Finder", cat: "security", desc: "Approximate location for an IP address.", icon: "📍" },
  { slug: "ssl-certificate-checker", name: "SSL Certificate Checker", cat: "security", desc: "Probe HTTPS reachability for a host.", icon: "🛡️" },
  { slug: "whois-lookup", name: "Whois Lookup", cat: "security", desc: "RDAP domain registration data.", icon: "📇" },
  { slug: "http-headers-checker", name: "HTTP Headers Checker", cat: "security", desc: "Fetch response headers when CORS allows.", icon: "📋" },
  { slug: "privacy-policy-generator", name: "Privacy Policy Generator", cat: "security", desc: "Draft a starter privacy policy.", icon: "📜" },
  { slug: "youtube-thumbnail-downloader", name: "YouTube Thumbnail Downloader", cat: "social", desc: "Grab public YouTube thumbnail images.", icon: "▶️" },
  { slug: "instagram-photo-downloader", name: "Instagram Photo Downloader", cat: "social", desc: "Save a photo you already have as JPG/PNG.", icon: "📷" },
  { slug: "twitter-video-downloader", name: "Twitter Video Downloader", cat: "social", desc: "Save a video file from your device.", icon: "🐦" },
  { slug: "facebook-video-downloader", name: "Facebook Video Downloader", cat: "social", desc: "Re-save a local video without uploading it.", icon: "📘" },
  { slug: "tiktok-video-downloader", name: "TikTok Video Downloader", cat: "social", desc: "Keep a local copy of a video you own.", icon: "🎵" },
  { slug: "youtube-tags-extractor", name: "YouTube Tags Extractor", cat: "social", desc: "Extract keywords from pasted video source/HTML.", icon: "🏷️" },
  { slug: "hashtag-generator", name: "Hashtag Generator", cat: "social", desc: "Build hashtags from a topic.", icon: "#" },
  { slug: "social-media-post-generator", name: "Social Media Post Generator", cat: "social", desc: "Draft posts with hooks and CTAs.", icon: "📣" },
  { slug: "emoji-keyboard", name: "Emoji Keyboard", cat: "social", desc: "Copy emoji quickly from a grouped palette.", icon: "😊" },
  { slug: "twitter-character-counter", name: "Twitter Character Counter", cat: "social", desc: "Count a post against the 280-character limit.", icon: "🐦" },
  { slug: "barcode-generator", name: "Barcode Generator", cat: "misc", desc: "Code 128 barcode from text.", icon: "|||" },
  { slug: "meme-generator", name: "Meme Generator", cat: "misc", desc: "Add top and bottom captions to an image.", icon: "😂" },
  { slug: "resume-builder", name: "Resume Builder", cat: "misc", desc: "Fill a resume and print or save as HTML.", icon: "🧾" },
  { slug: "invoice-generator", name: "Invoice Generator", cat: "misc", desc: "Create a simple invoice you can print.", icon: "💵" },
  { slug: "business-name-generator", name: "Business Name Generator", cat: "misc", desc: "Mix words into brand-name ideas.", icon: "🏢" },
  { slug: "lottery-number-generator", name: "Lottery Number Generator", cat: "misc", desc: "Pick random lottery-style numbers.", icon: "🎟️" },
  { slug: "flip-a-coin", name: "Flip a Coin Simulator", cat: "misc", desc: "Heads or tails with a fair coin toss.", icon: "🪙" },
  { slug: "random-number-generator", name: "Random Number Generator", cat: "misc", desc: "Random integers in a range.", icon: "🎲" },
  { slug: "dice-roller", name: "Dice Roller Simulator", cat: "misc", desc: "Roll NdS dice and total them.", icon: "⚀" },
  { slug: "internet-speed-test", name: "Internet Speed Test", cat: "misc", desc: "Estimate download speed via a CDN file.", icon: "📶" },
  { slug: "daily-planner-creator", name: "Daily Planner Creator", cat: "misc", desc: "Plan hourly blocks and print the day.", icon: "📅" },
  { slug: "wedding-invitation-generator", name: "Wedding Invitation Generator", cat: "misc", desc: "Design a printable invitation card.", icon: "💍" },
  { slug: "story-plot-generator", name: "Story Plot Generator", cat: "misc", desc: "Random premise, conflict, and twist.", icon: "📖" },
  { slug: "ebook-creator", name: "E-book Creator", cat: "misc", desc: "Compile chapters into a printable book.", icon: "📗" },
  { slug: "ai-chatbot-demo", name: "AI Chatbot Demo", cat: "misc", desc: "Rule-based demo chatbot (no cloud model).", icon: "💬" },
  { slug: "ip-address-tracker", name: "IP Address Tracker", cat: "misc", desc: "Track your IP and a lookup history.", icon: "🛰️" },
  { slug: "fake-address-generator", name: "Fake Address Generator", cat: "misc", desc: "Placeholder addresses for testing UIs.", icon: "🏠" },
  { slug: "electric-bill-calculator", name: "Calculator for Electric Bills", cat: "misc", desc: "Estimate a bill from kWh and tariff.", icon: "💡" },
  { slug: "leap-year-checker", name: "Leap Year Checker", cat: "misc", desc: "Check whether a year is a leap year.", icon: "📆" },
  { slug: "name-numerology-calculator", name: "Name to Numerology Calculator", cat: "misc", desc: "Pythagorean name number from letters.", icon: "🔮" }
];

window.CATEGORIES = [
  { id: "image", title: "Image Tools" },
  { id: "seo", title: "SEO Tools" },
  { id: "text", title: "Text Tools" },
  { id: "developer", title: "Developer Tools" },
  { id: "calculators", title: "Math & Calculators" },
  { id: "converters", title: "Unit Converters" },
  { id: "security", title: "Security & Encryption" },
  { id: "social", title: "Social Media Tools" },
  { id: "misc", title: "Miscellaneous Tools" }
];
